### PR TITLE
#2 Multiple input dirs with symfony-demo tests

### PR DESCRIPTION
**Pull request by partikus**

### CODE REVIEW

**Comment by partikus** [comment]
@PGS-php/php-rze CR please folks

**Comment by partikus** [comment]
btw. would be nice to move `Jenkinsfile` to `Jenkinsfile.dist` to let users know that it's only a dist file

**Comment by tarnawski** [comment]
@partikus Your solution is very good and I would like to have them in project but is more complicated too. Complicated configuration is time consuming and will discourage others from using it. "Simpler is better" But it's only my opinion. I suggest tag basic version.

**Review by tarnawski — APPROVED** [review]
I like this solution :+1:

**Comment by partikus** [comment]
@tarnawski what is there too complicated? 
We can simplify that but I've introduced just two improvements:

1. moved logic from Jenkinsfile which is groovy script to external scripts
2. wrap logic blocks by functions 

thanks to that I could prepare testing scenario and do not duplicate the source code. 

Let's discuss

**Comment by tarnawski** [comment]
@partikus I wrote changes is good and I like it. But I afraid not all want spent time to know how it works. Also we can't simple copy-paste this code to Jenkins. Not all want to have Jenkinsfile in repo - in last refactor session almost everyone use "Pipline script" instead add file to project.

**Comment by partikus** [comment]
hm ... so maybe would better to create a short video tutorial (or step-by-step instructions) how to integrate this repo with jenkins?

apart from that we can create a `JenkinsfileInline` that contains all scripts inside single file. Does it make sense?

**Comment by tarnawski** [comment]
IMO `JenkinsfileInline` is good solution. We discuss about this in next refactor session.

**Comment by partikus** [comment]
@tarnawski please let me know what's the plan for this PR. 
should we merge it? any improvements needed? 

@dominikhajduk @dgrochowski @mateuszmaslanka ping

**Comment by tarnawski** [comment]
@partikus sorry for delay. According to our last discuss I working on prepare some summary document with ideas and propositions. I will send results to all on Monday. About PR - as I wrote for me is good to merge this. IMO no improvements required. Thanks!

**Review by dominikhajduk — APPROVED** [review]

**Pull request merged**
